# Set root of model run to analyze AND the model year
# Note that we need to use the full path and not the drive shortcut to be able to load sqlite db
run_dir = "N:/rtp_2026_2050/final_runs/sc_base_year_2023_final/soundcast"
run_dir_future = "N:/rtp_2026_2050/final_runs/sc_rtp_2035/soundcast"

output_root = "Y:/Air Quality/King County Emissions Inventory/2024"

base_year = "2023"    # Make sure to update this since rates used are based on this value
county_list = ["King", "Kitsap", "Pierce", "Snohomish"]

# Separate light duty vehicles by occupancy
include_light_modes = false

analysis_year_list = ["2023", "2024"]
lower_bound_year = "2023"
upper_bound_year = "2035"

pollutant_list = ["CO2 Equivalent", "Methane", "N20"]

[veh_type_map]
light = "Passenger Vehicles"
medium = "Medium Trucks"
heavy = "Heavy Trucks"
transit = "Bus"

# Bus Operators (excluding Sound Transit for now because they span multiple counties)
[county_transit_operators]
King = ["King County Metro"]
Pierce = ["Pierce Transit"]
Snohomish = ["Community Transit", "Everett Transit"]
Kitsap = ["Kitsap Transit"]